name: Export PATH to all steps

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PATH: $PATH:/path/you-would-like
    steps:
     - name: 'echo'
       run: echo $PATH
     - name: 'update?'
       run: sudo apt-get update -y
